cf2:
  initial_position:
  - 0.0
  - -0.5
  - 0.0
  type: cf21
  uri: radio://0/80/2M/E7E7E7E702
cf5:
  initial_position:
  - 0.5
  - 0.5
  - 0.0
  type: cf21
  uri: radio://0/80/2M/E7E7E7E705
cf6:
  initial_position:
  - -0.5
  - 0.5
  - 0.0
  type: cf21
  uri: radio://0/80/2M/E7E7E7E706
