# named list of all robots
robots:
  cf0000:
    enabled: true
    uri: radio://0/80/2M/E7E7E70000
    initial_position: [0.0, 0.0, 0.0]
    type: cf21  # see robot_types

  cf1111:
    enabled: false
    uri: radio://0/80/2M/E7E7E71111
    initial_position: [0.0, 0.5, 0.0]
    type: cf21  # see robot_types


  cf2222:
    enabled: false
    uri: radio://0/80/2M/E7E7E72222
    initial_position: [0.5, 0.0, 0.0]
    type: cf21  # see robot_types


  cf3333:
    enabled: false
    uri: radio://0/80/2M/E7E7E73333
    initial_position: [0.5, 0.5, 0.0]
    type: cf21  # see robot_types

  
  cf4444:
    enabled: false
    uri: radio://0/80/2M/E7E7E74444
    initial_position: [1.0, 0.0, 0.0]
    type: cf21  # see robot_types


  cf5555:
    enabled: false
    uri: radio://0/80/2M/E7E7E75555
    initial_position: [0.0, 1.0, 0.0]
    type: cf21  # see robot_types

  cf6666:
    enabled: false
    uri: radio://0/80/2M/E7E7E76666
    initial_position: [0.5, -0.5, 0.0]
    type: cf21  # see robot_types

  cf7777:
    enabled: false
    uri: radio://0/80/2M/E7E7E77777
    initial_position: [-0.5, 0.5, 0.0]
    type: cf21  # see robot_types

  cf8888:
    enabled: false
    uri: radio://0/80/2M/E7E7E78888
    initial_position: [1.5, -1.5, 0.0]
    type: cf21  # see robot_types

  cf9999:
    enabled: false
    uri: radio://0/80/2M/E7E7E79999
    initial_position: [-1.5, -1.5, 0.0]
    type: cf21  # see robot_types


# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: big_frame
      dynamics: default
    big_quad: true
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  cf21_mocap_deck:
    motion_capture:
      enabled: false
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 10 # Hz
      status:
        frequency: 1 # Hz
    custom_topics:
      posVelAcc:
        frequency: 100 # Hz
        vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.vx", "stateEstimateZ.vy","stateEstimateZ.ax", "stateEstimateZ.ay"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
