/crazyflie_server:
  ros__parameters:
    # simulation related
    sim:
      max_dt: 0 #0.1              # artificially limit the step() function (set to 0 to disable)
      backend: np                 # see backend folder for a list 
      visualizations:             # see visualization folder for a list
        rviz:
          enabled: true
        pdf:
          enabled: false
          output_file: "result.pdf"
        blender:
          enabled: false
          interval: 400    # number of time steps between taking images
          cf_cameras:      # names of crazyflies with cameras on them if enabled in `crazyflies.yaml`
            cf231:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [1.2092,-1.2092,1.2092]
            cf5:
              calibration:
                camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
                dist_coeff: [0,0,0,0,0]
                tvec: [0,0,0]
                rvec: [1.2092,-1.2092,1.2092]
          observer:        # static observer camera 
            enabled: true
            pos: [-0.1,0,1]
            quat: [1,0,0,0]
            calibration:
              camera_matrix: [170.0, 0.0, 160.0, 0.0, 170.0, 160.0, 0.0, 0.0, 1.0] # matrix in row-major order
              dist_coeff: [0,0,0,0,0]
              tvec: [0,0,0]
              rvec: [1.2092,-1.2092,1.2092]
      controller: mellinger # none, pid, mellinger
